# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taskapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20, validators=[taskapp.validators.validate_city])),
                ('state', models.CharField(max_length=20, validators=[taskapp.validators.validate_state])),
                ('landmark', models.CharField(max_length=50, validators=[taskapp.validators.validate_landmark])),
                ('pincode', models.CharField(max_length=10, validators=[taskapp.validators.validate_pincode])),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15, validators=[taskapp.validators.validate_mobile_no])),
                ('phone_no', models.CharField(max_length=15, validators=[taskapp.validators.validate_phone_no])),
                ('email_id', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='taskapp.ContactInfo')),
                ('cuid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15, validators=[taskapp.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=15, validators=[taskapp.validators.validate_last_name])),
                ('age', models.CharField(max_length=2, validators=[taskapp.validators.validate_age])),
                ('Addresses', models.ManyToManyField(to='taskapp.Address')),
            ],
            bases=('taskapp.contactinfo',),
        ),
    ]
